HOST lewis.lbl.gov
only_i 312
only_code None
force_amber_prep True
dry_run False
... 312 3oiu
/net/chevy/raid1/nigel/amber/hi_lo
/net/chevy/raid1/nigel/amber/hi_lo/oi/3oiu
3oiu.pdb 4phenix_3oiu.pdb
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/oi/pdb3oiu.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/oi/3oiu/3oiu.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/oi/pdb3oiu.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/oi/3oiu/3oiu.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

==================================================
Summary of pdb4amber for: 3oiu.pdb
===================================================

----------Chains
The following (original) chains have been found:
A

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
SER_39
TYR_40
ILE_142
GLU_143
GLU_153

---------- Mising heavy atom(s)

GLU_62 misses 4 heavy atom(s)
GLU_63 misses 4 heavy atom(s)
The alternate coordinates have been discarded.
Only the first occurrence for each atom was kept.
not prmtop_filename /net/lewis/scratch1/nigel/amber/hi_lo/oi/3oiu/4amber_3oiu.prmtop
not prmtop_filename /net/chevy/raid1/nigel/amber/hi_lo/oi/3oiu/4amber_3oiu.prmtop

	Running AmberPrep : 3oiu.pdb


==================================================
Running pdb4amber on 3oiu.pdb
==================================================

==================================================
Setting up library files for non-standard residues
==================================================

==================================================
Running elbow/antechamber for GNP 
==================================================

==================================================
Summary of pdb4amber for: 3oiu_4tleap_uc1.pdb
===================================================

----------Chains
The following (original) chains have been found:
A

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
None

---------- Mising heavy atom(s)

None

MoleculeClass :  C:10  N: 6  O:13  P: 3 (CHEMICAL COMPONENTS format)
	45 atoms
	47 bonds
	82 angles
	114 dihedrals
	2 rings (groups, rings, atoms) 3 16
	4 chirals : R S R R 

~> antechamber -i 4antechamber_GNP.pdb -fi pdb -o GNP.mol2 -fo mol2       -nc -4 -m 1 -s 2 -pf y -c bcc -at gaff2 -ek "qm_theory='AM1',grms_tol=0.0005,scfconv=1.d-10,maxcyc=0,ndiis_attempts=700,"


~> parmchk2 -s 2 -i GNP.mol2 -f mol2 -o GNP.frcmod


  Residue "ACT" already in amber monomer library. Skipping elbow/antechamber
    run for this residue.
        

==================================================
Preparing asu files and 4phenix_3oiu.pdb
==================================================

~> tleap -f 3oiu_asu_tleap_input_run

Checking output filenames
  file : 3oiu_asu.prmtop
  file : 3oiu_asu.rst7

~> ChBox -c 3oiu_asu.rst7 -o 3oiu_asu.rst7 -X 87.985 -Y 87.985 -Z 135.146 -al 90.0 -bt 90.0 -gm 120.0 


============================================================
Preparing unit cell files: 4amber_3oiu.prmtop and 4amber_3oiu.rst7
============================================================

~> UnitCell -p 3oiu_4UnitCell.pdb -o 3oiu_4tleap_uc1.pdb


~> tleap -f 3oiu_uc_tleap_input_run

Checking output filenames
  file : 3oiu_uc.prmtop
  file : 3oiu_uc.rst7

~> ChBox -c 3oiu_uc.rst7 -o 3oiu_uc.rst7 -X 87.985 -Y 87.985 -Z 135.146 -al 90.0 -bt 90.0 -gm 120.0 


==================================================
Minimizing input coordinates.
==================================================

~> sander -O -i 3oiu_amber_all.in -p 4amber_3oiu.prmtop -c 4amber_3oiu.rst7 -o 3oiu.min.out            -ref 4amber_3oiu.rst7 -r 4amber_3oiu.min.rst7

Traceback (most recent call last):
  File "run_tests_local.py", line 323, in <module>
    run(*tuple(args))
  File "run_tests_local.py", line 307, in run
    w2 = run_all_tests(code, force_amber_prep=force_amber_prep)
  File "run_tests_local.py", line 93, in run_all_tests
    "clean=on",
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 1034, in run
    minimization_options=actions.minimization_options)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber_adaptbx/command_line/AmberPrepClass.py", line 685, in run_minimise
    assert (ero.return_code == 0)
AssertionError
