HOST lewis.lbl.gov
only_i 340
only_code None
force_amber_prep True
dry_run False
... 340 3o41
/net/chevy/raid1/nigel/amber/hi_lo
/net/chevy/raid1/nigel/amber/hi_lo/o4/3o41
3o41.pdb 4phenix_3o41.pdb
local_archive None
archive PDB None
Reading from local mirror:
  /net/cci/pdb_mirror/pdb/o4/pdb3o41.ent.gz
Model saved to /net/lewis/raid1/scratch1/nigel/amber/hi_lo/o4/3o41/3o41.pdb
Traceback (most recent call last):
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 199, in <module>
    run2(sys.argv[1:])
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/build/../modules/cctbx_project/mmtbx/command_line/fetch_pdb.py", line 155, in run2
    files.append(get_pdb(id, data_type_, mirror, log, format=data_format))
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 213, in get_pdb
    data = fetch(id, data_type, mirror=mirror, format=format, log=log)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/iotbx/pdb/fetch.py", line 150, in fetch
    data = libtbx.utils.urlopen(url)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/cctbx_project/libtbx/utils.py", line 2069, in urlopen
    return urllib2.urlopen(*args, **kwds)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/net/cci-filer2/raid1/xp/phenix/phenix-svn/base/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

==================================================
Summary of pdb4amber for: 3o41.pdb
===================================================

----------Chains
The following (original) chains have been found:
A
B
C
H
L
P

---------- Alternate Locations (Original Residues!))

The following residues had alternate locations:
None

---------- Gaps (Renumbered Residues!)
gap of 10.278800 A between ALA 574 and ASN 575
gap of 72.076436 A between SER 882 and ASN 884

---------- Mising heavy atom(s)

None
not prmtop_filename /net/lewis/scratch1/nigel/amber/hi_lo/o4/3o41/4amber_3o41.prmtop
not prmtop_filename /net/chevy/raid1/nigel/amber/hi_lo/o4/3o41/4amber_3o41.prmtop

	Running AmberPrep : 3o41.pdb


==================================================
Running pdb4amber on 3o41.pdb
==================================================

==================================================
Setting up library files for non-standard residues
==================================================

  Residue "SO4" already in amber monomer library. Skipping elbow/antechamber
    run for this residue.
        

==================================================
Running elbow/antechamber for NH2 
==================================================

MoleculeClass :  N: 1 (CHEMICAL COMPONENTS format)
	3 atoms
	2 bonds
	1 angles
	0 dihedrals
	0 rings (groups, rings, atoms) 0 0
	0 chirals

~> antechamber -i 4antechamber_NH2.pdb -fi pdb -o NH2.mol2 -fo mol2       -nc 0 -m 2 -s 2 -pf y -c bcc -at gaff2 -ek "qm_theory='AM1',grms_tol=0.0005,scfconv=1.d-10,maxcyc=0,ndiis_attempts=700,"

Sorry: Error: cannot run "/net/cci-filer2/raid1/xp/phenix/phenix-svn/modules/amber/bin/sqm -O -i sqm.in -o sqm.out" of bcc() in charge.c properly, exit
